// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qovokxahmfburzcvndex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdm9reGFobWZidXJ6Y3ZuZGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjEyODksImV4cCI6MjA2MDYzNzI4OX0.ceNig0kcrKm63q4GnizijHiliDDr34Peye4op2vnEG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);